[build]
  command = "npm run build"
  functions = "functions/built/" # netlify dev uses this to know where to scaffold and serve your functions
  publish = "static"

[dev]
  publish = "static"

[[redirects]]
  force = true
  from = '/api/*'
  status = 200
  to = '/.netlify/functions/:splat'